# Generated by Django 5.2.9 on 2025-12-13 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('room_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('doctor_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medicine_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounts.patient')),
            ],
        ),
    ]
