# Generated by Django 5.2.9 on 2025-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_payment_method_bill_payment_status_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='doctor_fees',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='medicine_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='room_charges',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
