# Generated by Django 5.2.9 on 2025-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patient_user_alter_doctor_id_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default='50.00', max_digits=10),
        ),
    ]
