# Generated by Django 5.2.9 on 2025-12-21 00:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
    ]
